# -*- coding: utf-8 -*-
"""
seed_v7.py — Filières du Bénin reconstruites depuis les sources officielles
Sources : UAC, UP, UNSTIM, UNA, 35 EPES agréées MESRS (2019-2025)
Règle : 1 filière unique par domaine (pas de doublons internes)
Comportement idempotent : filière/formation déjà en base → skippée
"""
from sqlmodel import Session, select
from app.core.database import engine, create_db_and_tables
from app.models.filiere import Filiere
from app.models.universite import Universite
from app.models.formation import Formation

# ─── Filières ──────────────────────────────────────────────────────────────────
# Structure :
#   nom                    : str   — nom canonique unique
#   domaine                : str   — domaine (unique par filière)
#   duree_theorique        : int   — années (Licence=3, Master=5, Médecine=7…)
#   salaire_median_p50     : int   — FCFA/mois (estimations INSAE/marché 2024)
#   taux_insertion         : float — 0-100 (%)
#   indice_saturation      : float — 0-1 (1=très saturé)
#   tendance_ia            : int   — 0=croissance, 1=stable, 2=transformation, 3=affecté
#   tendance_curricula_marche : float — 0-1
#   profil_riasec_dominant : dict  — R I A S E C (0-100)
#   veto_factors           : dict
#   etablissements         : list  — clés de l'ETAB_MAP

FILIERES = [

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : ADMINISTRATION PUBLIQUE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Administration Générale',
        'domaine': 'Administration Publique',
        'duree_theorique': 3,
        'salaire_median_p50': 220000,
        'taux_insertion': 75.0,
        'indice_saturation': 0.75,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 15, "I": 60, "A": 30, "S": 65, "E": 60, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENA / UAC', 'ESAE Bénin', 'IUP Bénin'],
    },
    {
        'nom': 'Administration Financière',
        'domaine': 'Administration Publique',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 77.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 15, "I": 65, "A": 25, "S": 50, "E": 60, "C": 90},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENA / UAC'],
    },
    {
        'nom': 'Administration du Travail et Sécurité Sociale',
        'domaine': 'Administration Publique',
        'duree_theorique': 3,
        'salaire_median_p50': 210000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.40,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 15, "I": 55, "A": 20, "S": 75, "E": 55, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A","B","C","D","G2","G3"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENA / UAC'],
    },
    {
        'nom': 'Planification et Développement Local',
        'domaine': 'Administration Publique',
        'duree_theorique': 3,
        'salaire_median_p50': 215000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.50,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 20, "I": 65, "A": 30, "S": 65, "E": 60, "C": 75},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENA / UAC'],
    },
    {
        'nom': 'Diplomatie et Relations Internationales',
        'domaine': 'Administration Publique',
        'duree_theorique': 3,
        'salaire_median_p50': 280000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.60,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 45, "S": 75, "E": 80, "C": 60},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENA / UAC'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : AGRICULTURE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Agronomie Générale',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 180000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.45,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 80, "I": 65, "A": 25, "S": 45, "E": 50, "C": 50},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'FA / UP', 'UATM GASA Formation'],
    },
    {
        'nom': 'Production Végétale et Semencière',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 170000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.40,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 85, "I": 60, "A": 20, "S": 40, "E": 45, "C": 55},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'UNA'],
    },
    {
        'nom': 'Production et Santé Animales',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 175000,
        'taux_insertion': 66.0,
        'indice_saturation': 0.38,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.73,
        'profil_riasec_dominant': {"R": 80, "I": 60, "A": 20, "S": 50, "E": 45, "C": 50},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'FA / UP', 'UNA'],
    },
    {
        'nom': 'Nutrition Humaine et Agroalimentaire',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 185000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.35,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 55, "I": 70, "A": 30, "S": 60, "E": 45, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'UNA'],
    },
    {
        'nom': 'Conseil Agricole et Gestion des Exploitations',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 165000,
        'taux_insertion': 63.0,
        'indice_saturation': 0.42,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 70, "I": 55, "A": 25, "S": 65, "E": 60, "C": 55},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC'],
    },
    {
        'nom': 'Agroéconomie et Développement Rural',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 175000,
        'taux_insertion': 64.0,
        'indice_saturation': 0.45,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 50, "I": 70, "A": 30, "S": 60, "E": 55, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'UNA'],
    },
    {
        'nom': 'Génie Rural et Eaux-Forêts',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.74,
        'profil_riasec_dominant': {"R": 80, "I": 65, "A": 20, "S": 40, "E": 45, "C": 55},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC'],
    },
    {
        'nom': 'Horticulture et Aménagement des Espaces Verts',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 160000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 85, "I": 55, "A": 50, "S": 45, "E": 40, "C": 45},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UNA'],
    },
    {
        'nom': 'Machinisme Agricole et Mécanique',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 185000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 90, "I": 60, "A": 20, "S": 30, "E": 40, "C": 55},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UNA'],
    },
    {
        'nom': 'Pêche et Aquaculture',
        'domaine': 'Agriculture',
        'duree_theorique': 3,
        'salaire_median_p50': 165000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 80, "I": 60, "A": 25, "S": 45, "E": 40, "C": 50},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'UNA'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : ARTS ET CULTURE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Arts et Management Culturel',
        'domaine': 'Arts et Culture',
        'duree_theorique': 3,
        'salaire_median_p50': 130000,
        'taux_insertion': 45.0,
        'indice_saturation': 0.40,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 40, "I": 45, "A": 90, "S": 65, "E": 70, "C": 35},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FLLAC / UAC'],
    },
    {
        'nom': 'Réalisation Audiovisuelle',
        'domaine': 'Arts et Culture',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 52.0,
        'indice_saturation': 0.50,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 50, "I": 55, "A": 90, "S": 55, "E": 65, "C": 40},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 400000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTIC / UAC', 'ISMA Bénin'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : COMMERCE ET MARKETING
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Marketing et Action Commerciale',
        'domaine': 'Commerce et Marketing',
        'duree_theorique': 3,
        'salaire_median_p50': 175000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.75,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 20, "I": 55, "A": 55, "S": 70, "E": 85, "C": 60},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC', 'ESEP Le Beger', 'Les Cours Sonou',
                           'École Supérieure Sainte Félicité', 'École Supérieure Jean Michel Le Faucon',
                           'ISM Adonaï', 'ISEG Bénin'],
    },
    {
        'nom': 'Commerce International',
        'domaine': 'Commerce et Marketing',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.60,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 15, "I": 60, "A": 45, "S": 65, "E": 85, "C": 65},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC'],
    },
    {
        'nom': 'Négociation et Communication Multimédia',
        'domaine': 'Commerce et Marketing',
        'duree_theorique': 3,
        'salaire_median_p50': 165000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.65,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 20, "I": 55, "A": 65, "S": 70, "E": 80, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Pigier Bénin'],
    },
    {
        'nom': 'Hôtellerie Restauration et Tourisme',
        'domaine': 'Commerce et Marketing',
        'duree_theorique': 3,
        'salaire_median_p50': 150000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.45,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 40, "I": 40, "A": 60, "S": 80, "E": 75, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['École Supérieure Jean Michel Le Faucon', 'HECM Bénin',
                           'École Supérieure de Management (ESM)', 'ESPERANZA'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : COMMUNICATION ET MÉDIAS
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Journalisme et Communication',
        'domaine': 'Communication et Médias',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.70,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 15, "I": 55, "A": 75, "S": 70, "E": 65, "C": 40},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTIC / UAC', 'ESAE Bénin', 'Les Cours Sonou',
                           'ISCG Bénin', 'IUP Bénin', 'HECM Bénin'],
    },
    {
        'nom': "Communication d'Entreprise",
        'domaine': 'Communication et Médias',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.65,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 15, "I": 55, "A": 70, "S": 70, "E": 75, "C": 50},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Les Cours Sonou', 'ISMT Saint Salomon'],
    },
    {
        'nom': 'Communication et Relations Publiques',
        'domaine': 'Communication et Médias',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 56.0,
        'indice_saturation': 0.60,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.63,
        'profil_riasec_dominant': {"R": 15, "I": 55, "A": 70, "S": 75, "E": 72, "C": 45},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTIC / UAC', 'École Supérieure Sainte Félicité'],
    },
    {
        'nom': 'Communication et Action Publicitaire',
        'domaine': 'Communication et Médias',
        'duree_theorique': 3,
        'salaire_median_p50': 150000,
        'taux_insertion': 54.0,
        'indice_saturation': 0.60,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 20, "I": 50, "A": 80, "S": 65, "E": 75, "C": 45},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UCAO Bénin'],
    },
    {
        'nom': "Sciences et Techniques de l'Information",
        'domaine': 'Communication et Médias',
        'duree_theorique': 3,
        'salaire_median_p50': 148000,
        'taux_insertion': 54.0,
        'indice_saturation': 0.55,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 30, "I": 65, "A": 60, "S": 60, "E": 55, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTIC / UAC'],
    },
    {
        'nom': 'Communication Politique et Stratégique',
        'domaine': 'Communication et Médias',
        'duree_theorique': 5,
        'salaire_median_p50': 200000,
        'taux_insertion': 48.0,
        'indice_saturation': 0.40,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 70, "S": 75, "E": 85, "C": 50},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 500000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IIM Bénin'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : DROIT
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Droit Privé',
        'domaine': 'Droit',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.80,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 45, "S": 65, "E": 70, "C": 80},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FADESP / UAC', 'FDSP / UP'],
    },
    {
        'nom': 'Droit Public',
        'domaine': 'Droit',
        'duree_theorique': 3,
        'salaire_median_p50': 160000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.75,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 40, "S": 65, "E": 70, "C": 80},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FADESP / UAC', 'FDSP / UP'],
    },
    {
        'nom': 'Droit des Affaires',
        'domaine': 'Droit',
        'duree_theorique': 3,
        'salaire_median_p50': 180000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 40, "S": 60, "E": 80, "C": 80},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FADESP / UAC', 'ISM Adonaï', 'IIM Bénin'],
    },
    {
        'nom': 'Sciences Juridiques',
        'domaine': 'Droit',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.80,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 40, "S": 65, "E": 68, "C": 80},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'ISCG Bénin'],
    },
    {
        'nom': 'Fiscalité et Droit des Affaires',
        'domaine': 'Droit',
        'duree_theorique': 5,
        'salaire_median_p50': 230000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.45,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 10, "I": 80, "A": 35, "S": 55, "E": 75, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 450000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Pigier Bénin', 'HECM Bénin'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : ÉCONOMIE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Sciences Économiques',
        'domaine': 'Économie',
        'duree_theorique': 3,
        'salaire_median_p50': 185000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.70,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 10, "I": 85, "A": 35, "S": 55, "E": 65, "C": 75},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASEG / UAC', 'FADSEG / UP', 'IRGIB Africa Université', 'ESAE Bénin', 'ESCAE Bénin'],
    },
    {
        'nom': 'Statistique et Planification',
        'domaine': 'Économie',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.25,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.82,
        'profil_riasec_dominant': {"R": 15, "I": 95, "A": 20, "S": 35, "E": 45, "C": 80},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC'],
    },
    {
        'nom': 'Économie Publique et Statistique',
        'domaine': 'Économie',
        'duree_theorique': 5,
        'salaire_median_p50': 280000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.20,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.82,
        'profil_riasec_dominant': {"R": 10, "I": 90, "A": 25, "S": 40, "E": 55, "C": 82},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 500000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['African School of Economics (ASE)'],
    },
    {
        'nom': 'Modélisation Aléatoire, Statistique et Finances',
        'domaine': 'Économie',
        'duree_theorique': 5,
        'salaire_median_p50': 320000,
        'taux_insertion': 82.0,
        'indice_saturation': 0.15,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.90,
        'profil_riasec_dominant': {"R": 10, "I": 95, "A": 20, "S": 30, "E": 50, "C": 85},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSGMM / UNSTIM'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : ÉDUCATION ET PÉDAGOGIE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'CAPES Lettres Modernes',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 85.0,
        'indice_saturation': 0.35,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 10, "I": 60, "A": 70, "S": 85, "E": 45, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC', 'EFES Sapientia'],
    },
    {
        'nom': 'CAPES Anglais',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 148000,
        'taux_insertion': 87.0,
        'indice_saturation': 0.30,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 10, "I": 60, "A": 65, "S": 85, "E": 45, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC'],
    },
    {
        'nom': 'CAPES Histoire-Géographie',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 142000,
        'taux_insertion': 83.0,
        'indice_saturation': 0.40,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 55, "S": 82, "E": 42, "C": 60},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC', 'EFES Sapientia'],
    },
    {
        'nom': 'CAPES Philosophie',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 140000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.45,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 65, "S": 80, "E": 40, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC', 'EFES Sapientia'],
    },
    {
        'nom': 'CAPES Sciences de Vie et de la Terre',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 86.0,
        'indice_saturation': 0.30,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 30, "I": 80, "A": 40, "S": 82, "E": 40, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC', 'EFES Sapientia'],
    },
    {
        'nom': 'BAPES / CAPES Mathématiques-Informatique',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 150000,
        'taux_insertion': 90.0,
        'indice_saturation': 0.25,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 20, "I": 90, "A": 30, "S": 78, "E": 40, "C": 75},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENS / UAC', 'EFES Sapientia'],
    },
    {
        'nom': 'BAPES Physique-Chimie et Technologie',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 148000,
        'taux_insertion': 88.0,
        'indice_saturation': 0.28,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 30, "I": 88, "A": 30, "S": 80, "E": 38, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EFES Sapientia'],
    },
    {
        'nom': 'BAPES Sciences et Vie de la Terre',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 87.0,
        'indice_saturation': 0.30,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 35, "I": 82, "A": 30, "S": 82, "E": 38, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EFES Sapientia'],
    },
    {
        'nom': 'BAPES Éducation Physique et Sportive',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 135000,
        'taux_insertion': 82.0,
        'indice_saturation': 0.35,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 75, "I": 40, "A": 40, "S": 82, "E": 50, "C": 45},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EFES Sapientia'],
    },
    {
        'nom': "Sciences de l'Éducation",
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 130000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 45, "S": 88, "E": 45, "C": 60},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'UPAO Bénin'],
    },
    {
        'nom': 'Éducation et Pédagogie',
        'domaine': 'Éducation et Pédagogie',
        'duree_theorique': 3,
        'salaire_median_p50': 130000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.60,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 60, "A": 50, "S": 88, "E": 45, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UPAO Bénin', 'ENS Natitingou / UNSTIM'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : ENVIRONNEMENT
    # ══════════════════════════════════════════════════════════════
    {
        'nom': "Gestion de l'Environnement et Aménagement",
        'domaine': 'Environnement',
        'duree_theorique': 3,
        'salaire_median_p50': 185000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.40,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 55, "I": 75, "A": 35, "S": 55, "E": 55, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSA / UAC', 'UCAO Bénin'],
    },
    {
        'nom': "Génie de l'Environnement",
        'domaine': 'Environnement',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.35,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 60, "I": 80, "A": 30, "S": 50, "E": 50, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC'],
    },
    {
        'nom': 'Sciences et Techniques des Eaux',
        'domaine': 'Environnement',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 65, "I": 80, "A": 25, "S": 45, "E": 48, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },
    {
        'nom': 'Hygiène Nutrition Santé et Environnement',
        'domaine': 'Environnement',
        'duree_theorique': 3,
        'salaire_median_p50': 175000,
        'taux_insertion': 64.0,
        'indice_saturation': 0.35,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 45, "I": 75, "A": 30, "S": 70, "E": 45, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IRGIB Africa Université'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : FINANCE ET COMPTABILITÉ
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Banque Finance et Assurance',
        'domaine': 'Finance et Comptabilité',
        'duree_theorique': 3,
        'salaire_median_p50': 225000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.80,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 30, "S": 50, "E": 75, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'Les Cours Sonou', 'École Supérieure Sainte Félicité',
                           'École Supérieure Jean Michel Le Faucon', 'ISM Adonaï', 'ISEG Bénin',
                           'UPI-ONM Bénin', 'ESEP Le Beger', 'HECM Bénin', 'UCAO Bénin',
                           'UPAO Bénin', 'Pigier Bénin', 'École Supérieure de Management (ESM)',
                           'ISCG Bénin', 'ESGIS Bénin'],
    },
    {
        'nom': 'Comptabilité Contrôle et Audit',
        'domaine': 'Finance et Comptabilité',
        'duree_theorique': 3,
        'salaire_median_p50': 215000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.85,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.73,
        'profil_riasec_dominant': {"R": 10, "I": 80, "A": 25, "S": 45, "E": 65, "C": 90},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESGIS Bénin', 'ESCAE Bénin', 'ISCG Bénin', 'ISM Adonaï', 'ISEG Bénin',
                           'ISMT Saint Salomon', 'UPAO Bénin', 'UPI-ONM Bénin', 'CIFEC Bénin'],
    },
    {
        'nom': 'Finance et Contrôle de Gestion',
        'domaine': 'Finance et Comptabilité',
        'duree_theorique': 3,
        'salaire_median_p50': 230000,
        'taux_insertion': 73.0,
        'indice_saturation': 0.70,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 10, "I": 82, "A": 28, "S": 45, "E": 70, "C": 88},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASEG / UAC', 'ENEAM / UAC', 'HECM Bénin',
                           'École Supérieure de Management (ESM)', 'IUST-AS Bénin', 'ESEP Le Beger'],
    },
    {
        'nom': 'Techniques Comptables et Financières',
        'domaine': 'Finance et Comptabilité',
        'duree_theorique': 3,
        'salaire_median_p50': 200000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.75,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 10, "I": 78, "A": 25, "S": 42, "E": 60, "C": 88},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UPI-ONM Bénin', 'CIFEC Bénin'],
    },
    {
        'nom': 'Gestion Financière et Comptable',
        'domaine': 'Finance et Comptabilité',
        'duree_theorique': 3,
        'salaire_median_p50': 205000,
        'taux_insertion': 67.0,
        'indice_saturation': 0.75,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 10, "I": 78, "A": 26, "S": 44, "E": 62, "C": 88},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : GESTION ET MANAGEMENT
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Gestion des Ressources Humaines',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.80,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 10, "I": 60, "A": 40, "S": 80, "E": 72, "C": 70},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC', 'UATM GASA Formation', 'ESCAE Bénin', 'Les Cours Sonou',
                           'UPI-ONM Bénin', 'UCAO Bénin', 'UPAO Bénin', 'ESEP Le Beger',
                           'ESGIS Bénin', 'ISM Adonaï', 'ISEG Bénin', 'IIM Bénin',
                           'Pigier Bénin', 'ISCG Bénin', 'HECM Bénin', 'ISMT Saint Salomon'],
    },
    {
        'nom': 'Management des Entreprises',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 200000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.90,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 15, "I": 65, "A": 40, "S": 65, "E": 85, "C": 70},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC', 'IIM Bénin', 'Pigier Bénin', 'FADSEG / UP'],
    },
    {
        'nom': 'Administration et Gestion des Entreprises',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.90,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 15, "I": 62, "A": 38, "S": 62, "E": 82, "C": 72},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['HECM Bénin', 'École Supérieure de Management (ESM)', 'FADSEG / UP'],
    },
    {
        'nom': 'Entrepreneuriat et Gestion des PME',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 180000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.60,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 30, "I": 60, "A": 50, "S": 60, "E": 90, "C": 60},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'ISM Adonaï', 'Les Cours Sonou',
                           'IUST-AS Bénin', 'ESPERANZA'],
    },
    {
        'nom': 'Gestion de Projets',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 210000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.55,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 25, "I": 70, "A": 40, "S": 60, "E": 80, "C": 75},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESGIS Bénin', 'IIM Bénin', 'Les Cours Sonou', 'Pigier Bénin'],
    },
    {
        'nom': 'Management International',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 225000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.55,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 10, "I": 68, "A": 48, "S": 65, "E": 88, "C": 70},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 400000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESGIS Bénin'],
    },
    {
        'nom': 'Sciences de Gestion',
        'domaine': 'Gestion et Management',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.80,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 35, "S": 55, "E": 72, "C": 80},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASEG / UAC', 'ESAE Bénin'],
    },
    {
        'nom': 'Intelligence Économique et Stratégie',
        'domaine': 'Gestion et Management',
        'duree_theorique': 5,
        'salaire_median_p50': 280000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.30,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.82,
        'profil_riasec_dominant': {"R": 15, "I": 85, "A": 45, "S": 55, "E": 85, "C": 75},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 500000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IIM Bénin'],
    },
    {
        'nom': 'Gestion des Marchés Publics',
        'domaine': 'Gestion et Management',
        'duree_theorique': 5,
        'salaire_median_p50': 260000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.25,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 10, "I": 75, "A": 30, "S": 55, "E": 72, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 450000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IIM Bénin'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : INFORMATIQUE ET NUMÉRIQUE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Génie Informatique et Télécommunications',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 250000,
        'taux_insertion': 88.0,
        'indice_saturation': 0.30,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.85,
        'profil_riasec_dominant': {"R": 70, "I": 90, "A": 35, "S": 25, "E": 55, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'UPAO Bénin'],
    },
    {
        'nom': 'Intelligence Artificielle et Data Science',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 320000,
        'taux_insertion': 92.0,
        'indice_saturation': 0.10,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.95,
        'profil_riasec_dominant': {"R": 55, "I": 95, "A": 40, "S": 25, "E": 55, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IFRI / UAC'],
    },
    {
        'nom': 'Informatique de Gestion',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 200000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.55,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 50, "I": 82, "A": 30, "S": 35, "E": 55, "C": 75},
        'veto_factors': {"serie_bac_requise": ["C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC', 'UCAO Bénin', 'IUT / UP'],
    },
    {
        'nom': 'Informatique Réseaux et Télécommunication',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 230000,
        'taux_insertion': 85.0,
        'indice_saturation': 0.35,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.82,
        'profil_riasec_dominant': {"R": 65, "I": 88, "A": 28, "S": 25, "E": 50, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESGIS Bénin', 'UPI-ONM Bénin', 'UATM GASA Formation',
                           'UCAO Bénin', 'UPAO Bénin'],
    },
    {
        'nom': 'Système Informatique et Logiciel',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 240000,
        'taux_insertion': 87.0,
        'indice_saturation': 0.30,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.85,
        'profil_riasec_dominant': {"R": 60, "I": 90, "A": 35, "S": 22, "E": 50, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'École Supérieure Jean Michel Le Faucon', 'IUST-AS Bénin'],
    },
    {
        'nom': 'Génie Télécoms et TIC',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 85.0,
        'indice_saturation': 0.30,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.83,
        'profil_riasec_dominant': {"R": 65, "I": 88, "A": 30, "S": 22, "E": 50, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESGTIC Bénin', 'HECM Bénin'],
    },
    {
        'nom': 'Réseaux et Génie Logiciel',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 85.0,
        'indice_saturation': 0.30,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.84,
        'profil_riasec_dominant': {"R": 60, "I": 90, "A": 32, "S": 22, "E": 48, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Pigier Bénin'],
    },
    {
        'nom': 'Modélisation et Simulation Numérique',
        'domaine': 'Informatique et Numérique',
        'duree_theorique': 5,
        'salaire_median_p50': 310000,
        'taux_insertion': 88.0,
        'indice_saturation': 0.12,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.92,
        'profil_riasec_dominant': {"R": 45, "I": 95, "A": 38, "S": 22, "E": 48, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSGMM / UNSTIM'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : INGÉNIERIE ET TECHNOLOGIE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Génie Civil et BTP',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 5,
        'salaire_median_p50': 280000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.40,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 88, "I": 72, "A": 35, "S": 28, "E": 55, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'ENSTP / UNSTIM', 'VERECHAGUINE', 'POLYTECH ADA'],
    },
    {
        'nom': 'Architecture et Urbanisme',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 5,
        'salaire_median_p50': 265000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 70, "I": 70, "A": 85, "S": 40, "E": 60, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTP / UNSTIM'],
    },
    {
        'nom': 'Génie Électrique et Automatisme',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 255000,
        'taux_insertion': 82.0,
        'indice_saturation': 0.32,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 85, "I": 82, "A": 25, "S": 22, "E": 48, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'INSTI / UNSTIM', 'IUST-AS Bénin'],
    },
    {
        'nom': 'Génie Électronique et Télécommunications',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 248000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.33,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 82, "I": 85, "A": 25, "S": 20, "E": 48, "C": 62},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'UCAO Bénin'],
    },
    {
        'nom': 'Génie Mécanique et Énergétique',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 245000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.35,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.76,
        'profil_riasec_dominant': {"R": 88, "I": 78, "A": 22, "S": 22, "E": 48, "C": 62},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'INSPEI / UNSTIM'],
    },
    {
        'nom': 'Génie Énergétique et Énergies Renouvelables',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 255000,
        'taux_insertion': 82.0,
        'indice_saturation': 0.22,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.88,
        'profil_riasec_dominant': {"R": 80, "I": 82, "A": 28, "S": 28, "E": 52, "C": 62},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSGEP / UNSTIM', 'ESMER Bénin'],
    },
    {
        'nom': 'Génie Frigorifique et Climatisation',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.82,
        'profil_riasec_dominant': {"R": 85, "I": 75, "A": 22, "S": 22, "E": 45, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSGEP / UNSTIM', 'ESMER Bénin'],
    },
    {
        'nom': "Génie de l'Eau et Hydraulique",
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 240000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.28,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 75, "I": 80, "A": 22, "S": 32, "E": 48, "C": 62},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'VERECHAGUINE', 'ENSTP / UNSTIM'],
    },
    {
        'nom': 'Génie de la Maintenance Industrielle',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 238000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.28,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 88, "I": 75, "A": 20, "S": 22, "E": 45, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'INSTI / UNSTIM'],
    },
    {
        'nom': 'Génie des Procédés Industriels',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 240000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 85, "I": 80, "A": 22, "S": 22, "E": 45, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC', 'IRGIB Africa Université'],
    },
    {
        'nom': 'Système Industriel et Automatisation',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 242000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.80,
        'profil_riasec_dominant': {"R": 85, "I": 82, "A": 22, "S": 20, "E": 45, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'INSTI / UNSTIM'],
    },
    {
        'nom': 'Géomètre Topographe',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 235000,
        'taux_insertion': 82.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 80, "I": 78, "A": 30, "S": 28, "E": 48, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ESIGT Bénin', 'VERECHAGUINE', 'École Supérieure Jean Michel Le Faucon'],
    },
    {
        'nom': 'Génie Biomédical',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 260000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.20,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.85,
        'profil_riasec_dominant': {"R": 72, "I": 88, "A": 28, "S": 50, "E": 45, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['EPAC / UAC'],
    },
    {
        'nom': 'Contrôle Qualité et Génie Agroalimentaire',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 220000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.28,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 65, "I": 80, "A": 28, "S": 45, "E": 48, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['HECM Bénin'],
    },
    {
        'nom': 'Génie des Expertises et Analyses',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 3,
        'salaire_median_p50': 230000,
        'taux_insertion': 75.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 65, "I": 85, "A": 25, "S": 40, "E": 45, "C": 75},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IRGIB Africa Université'],
    },
    {
        'nom': 'Transport et Territoire',
        'domaine': 'Ingénierie et Technologie',
        'duree_theorique': 5,
        'salaire_median_p50': 255000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 72, "I": 72, "A": 30, "S": 38, "E": 55, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D","E"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENSTP / UNSTIM'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : LANGUES ET LETTRES
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Lettres Modernes',
        'domaine': 'Langues et Lettres',
        'duree_theorique': 3,
        'salaire_median_p50': 115000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.70,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.50,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 82, "S": 65, "E": 40, "C": 50},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FLLAC / UAC', 'FLASH / UP'],
    },
    {
        'nom': 'Philosophie',
        'domaine': 'Langues et Lettres',
        'duree_theorique': 3,
        'salaire_median_p50': 110000,
        'taux_insertion': 48.0,
        'indice_saturation': 0.55,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.45,
        'profil_riasec_dominant': {"R": 8, "I": 80, "A": 75, "S": 65, "E": 42, "C": 48},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'Institut Jean Paul II'],
    },
    {
        'nom': 'Sciences du Langage et de la Communication',
        'domaine': 'Langues et Lettres',
        'duree_theorique': 3,
        'salaire_median_p50': 125000,
        'taux_insertion': 52.0,
        'indice_saturation': 0.55,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 10, "I": 68, "A": 75, "S": 72, "E": 45, "C": 52},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FLLAC / UAC'],
    },
    {
        'nom': 'Étude des Langues (Français, Anglais, Yoruba)',
        'domaine': 'Langues et Lettres',
        'duree_theorique': 3,
        'salaire_median_p50': 120000,
        'taux_insertion': 50.0,
        'indice_saturation': 0.50,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.55,
        'profil_riasec_dominant': {"R": 10, "I": 65, "A": 78, "S": 72, "E": 42, "C": 50},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IUP Bénin'],
    },
    {
        'nom': 'Traduction et Interprétation',
        'domaine': 'Langues et Lettres',
        'duree_theorique': 5,
        'salaire_median_p50': 175000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.35,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 10, "I": 72, "A": 75, "S": 68, "E": 48, "C": 58},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 400000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IUP Bénin'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : SANTÉ
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Médecine Humaine',
        'domaine': 'Santé',
        'duree_theorique': 7,
        'salaire_median_p50': 420000,
        'taux_insertion': 95.0,
        'indice_saturation': 0.12,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 40, "I": 85, "A": 25, "S": 88, "E": 38, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC', 'FM / UP'],
    },
    {
        'nom': 'Pharmacie',
        'domaine': 'Santé',
        'duree_theorique': 6,
        'salaire_median_p50': 330000,
        'taux_insertion': 90.0,
        'indice_saturation': 0.15,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 45, "I": 88, "A": 22, "S": 72, "E": 35, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC'],
    },
    {
        'nom': 'Odontostomatologie',
        'domaine': 'Santé',
        'duree_theorique': 7,
        'salaire_median_p50': 380000,
        'taux_insertion': 92.0,
        'indice_saturation': 0.12,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 55, "I": 82, "A": 35, "S": 80, "E": 38, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC'],
    },
    {
        'nom': 'Kinésithérapie',
        'domaine': 'Santé',
        'duree_theorique': 4,
        'salaire_median_p50': 260000,
        'taux_insertion': 85.0,
        'indice_saturation': 0.18,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 65, "I": 72, "A": 30, "S": 85, "E": 38, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC'],
    },
    {
        'nom': 'Nutrition et Diététique',
        'domaine': 'Santé',
        'duree_theorique': 3,
        'salaire_median_p50': 210000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.25,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 35, "I": 78, "A": 30, "S": 80, "E": 40, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC'],
    },
    {
        'nom': 'Sciences Infirmières et Obstétriques',
        'domaine': 'Santé',
        'duree_theorique': 3,
        'salaire_median_p50': 185000,
        'taux_insertion': 88.0,
        'indice_saturation': 0.18,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.70,
        'profil_riasec_dominant': {"R": 45, "I": 70, "A": 28, "S": 90, "E": 38, "C": 60},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC', 'IFSIO / UP'],
    },
    {
        'nom': 'Santé Publique',
        'domaine': 'Santé',
        'duree_theorique': 3,
        'salaire_median_p50': 200000,
        'taux_insertion': 75.0,
        'indice_saturation': 0.25,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 30, "I": 80, "A": 28, "S": 85, "E": 52, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IFSIO / UP'],
    },
    {
        'nom': 'Analyses Biomédicales',
        'domaine': 'Santé',
        'duree_theorique': 3,
        'salaire_median_p50': 220000,
        'taux_insertion': 80.0,
        'indice_saturation': 0.22,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 55, "I": 85, "A": 22, "S": 62, "E": 38, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IRGIB Africa Université', 'École Supérieure Jean Michel Le Faucon'],
    },
    {
        'nom': 'Travail Social et Action Communautaire',
        'domaine': 'Santé',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.45,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 25, "I": 55, "A": 35, "S": 92, "E": 52, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FSS / UAC'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : SCIENCES FONDAMENTALES
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Mathématiques',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 65.0,
        'indice_saturation': 0.45,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 15, "I": 95, "A": 28, "S": 38, "E": 42, "C": 78},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC', 'IMSP / UAC'],
    },
    {
        'nom': 'Physique',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.50,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 25, "I": 92, "A": 28, "S": 35, "E": 40, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },
    {
        'nom': 'Chimie',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 148000,
        'taux_insertion': 60.0,
        'indice_saturation': 0.50,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.68,
        'profil_riasec_dominant': {"R": 30, "I": 90, "A": 25, "S": 35, "E": 38, "C": 75},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },
    {
        'nom': 'Biologie',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 142000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.55,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 40, "I": 88, "A": 28, "S": 52, "E": 38, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },
    {
        'nom': 'Géologie',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 190000,
        'taux_insertion': 68.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.72,
        'profil_riasec_dominant': {"R": 60, "I": 88, "A": 28, "S": 35, "E": 42, "C": 65},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },
    {
        'nom': 'Biotechnologie',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 210000,
        'taux_insertion': 70.0,
        'indice_saturation': 0.25,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.85,
        'profil_riasec_dominant': {"R": 50, "I": 90, "A": 28, "S": 48, "E": 42, "C": 68},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC', 'UATM GASA Formation', 'UNA'],
    },
    {
        'nom': 'Mathématiques Appliquées',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 210000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.28,
        'tendance_ia': 0,
        'tendance_curricula_marche': 0.85,
        'profil_riasec_dominant': {"R": 15, "I": 95, "A": 25, "S": 32, "E": 45, "C": 80},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['IMSP / UAC', 'ENSGMM / UNSTIM'],
    },
    {
        'nom': 'Physique-Chimie',
        'domaine': 'Sciences Fondamentales',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 58.0,
        'indice_saturation': 0.52,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 28, "I": 90, "A": 25, "S": 35, "E": 38, "C": 72},
        'veto_factors': {"serie_bac_requise": ["C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FAST / UAC'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : SCIENCES SOCIALES ET HUMAINES
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Sociologie et Anthropologie',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 120000,
        'taux_insertion': 50.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.52,
        'profil_riasec_dominant': {"R": 12, "I": 75, "A": 55, "S": 82, "E": 48, "C": 52},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'FLASH / UP'],
    },
    {
        'nom': 'Histoire',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 112000,
        'taux_insertion': 48.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.48,
        'profil_riasec_dominant': {"R": 8, "I": 78, "A": 60, "S": 72, "E": 42, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'FLASH / UP'],
    },
    {
        'nom': 'Géographie et Aménagement du Territoire',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.55,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.60,
        'profil_riasec_dominant': {"R": 35, "I": 78, "A": 45, "S": 65, "E": 48, "C": 62},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'FLASH / UP'],
    },
    {
        'nom': "Psychologie et Sciences de l'Éducation",
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 130000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.60,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.62,
        'profil_riasec_dominant': {"R": 10, "I": 72, "A": 48, "S": 88, "E": 48, "C": 58},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FASHS / UAC', 'Institut Jean Paul II'],
    },
    {
        'nom': 'Science Politique et Relations Internationales',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 155000,
        'taux_insertion': 52.0,
        'indice_saturation': 0.65,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 8, "I": 78, "A": 52, "S": 75, "E": 78, "C": 62},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['FADESP / UAC', 'FDSP / UP', 'Les Cours Sonou', 'IRGIB Africa Université'],
    },
    {
        'nom': 'Sciences du Mariage et de la Famille',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 3,
        'salaire_median_p50': 115000,
        'taux_insertion': 42.0,
        'indice_saturation': 0.40,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.45,
        'profil_riasec_dominant': {"R": 8, "I": 62, "A": 48, "S": 90, "E": 40, "C": 52},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Institut Jean Paul II'],
    },
    {
        'nom': 'Théologie',
        'domaine': 'Sciences Sociales et Humaines',
        'duree_theorique': 4,
        'salaire_median_p50': 95000,
        'taux_insertion': 45.0,
        'indice_saturation': 0.35,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.40,
        'profil_riasec_dominant': {"R": 8, "I": 68, "A": 55, "S": 85, "E": 40, "C": 55},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['Institut Jean Paul II'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : SPORT ET ÉDUCATION PHYSIQUE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Sciences et Techniques des Activités Physiques et Sportives',
        'domaine': 'Sport et Éducation Physique',
        'duree_theorique': 3,
        'salaire_median_p50': 135000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.35,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 80, "I": 50, "A": 42, "S": 80, "E": 60, "C": 48},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D"], "budget_min_fcfa": 80000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['INJEPS / UAC', 'INJEPS / UP'],
    },
    {
        'nom': 'Management du Sport',
        'domaine': 'Sport et Éducation Physique',
        'duree_theorique': 3,
        'salaire_median_p50': 145000,
        'taux_insertion': 55.0,
        'indice_saturation': 0.40,
        'tendance_ia': 1,
        'tendance_curricula_marche': 0.65,
        'profil_riasec_dominant': {"R": 65, "I": 52, "A": 45, "S": 75, "E": 75, "C": 52},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['INJEPS / UAC'],
    },

    # ══════════════════════════════════════════════════════════════
    # DOMAINE : TRANSPORT ET LOGISTIQUE
    # ══════════════════════════════════════════════════════════════
    {
        'nom': 'Gestion des Transports et Logistique',
        'domaine': 'Transport et Logistique',
        'duree_theorique': 3,
        'salaire_median_p50': 195000,
        'taux_insertion': 72.0,
        'indice_saturation': 0.50,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.75,
        'profil_riasec_dominant': {"R": 35, "I": 65, "A": 35, "S": 52, "E": 75, "C": 72},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['ENEAM / UAC', 'UATM GASA Formation', 'UCAO Bénin', 'ESEP Le Beger',
                           'ISM Adonaï', 'ESGIS Bénin', 'Pigier Bénin', 'IUT / UP',
                           'École Supérieure Jean Michel Le Faucon', 'HECM Bénin'],
    },
    {
        'nom': 'Transport et Logistique Maritime',
        'domaine': 'Transport et Logistique',
        'duree_theorique': 3,
        'salaire_median_p50': 215000,
        'taux_insertion': 75.0,
        'indice_saturation': 0.30,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 40, "I": 65, "A": 32, "S": 48, "E": 72, "C": 72},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UATM GASA Formation', 'École Supérieure de Gestion Serena'],
    },
    {
        'nom': 'Métiers Portuaires et Douanes',
        'domaine': 'Transport et Logistique',
        'duree_theorique': 3,
        'salaire_median_p50': 225000,
        'taux_insertion': 78.0,
        'indice_saturation': 0.28,
        'tendance_ia': 2,
        'tendance_curricula_marche': 0.78,
        'profil_riasec_dominant': {"R": 38, "I": 65, "A": 30, "S": 48, "E": 72, "C": 75},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 350000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['École Supérieure de Gestion Serena'],
    },
    {
        'nom': 'Secrétariat de Direction',
        'domaine': 'Transport et Logistique',
        'duree_theorique': 3,
        'salaire_median_p50': 150000,
        'taux_insertion': 62.0,
        'indice_saturation': 0.60,
        'tendance_ia': 3,
        'tendance_curricula_marche': 0.58,
        'profil_riasec_dominant': {"R": 10, "I": 55, "A": 42, "S": 68, "E": 55, "C": 85},
        'veto_factors': {"serie_bac_requise": ["A1","A2","B","C","D","G"], "budget_min_fcfa": 300000},
        'poids_scoring': {'riasec': 0.60, 'marche': 0.25, 'ia': 0.15},
        'etablissements': ['UPAO Bénin'],
    },
]

# ─── ETAB_MAP ─────────────────────────────────────────────────────────────────
ETAB_MAP = {
    'ENA / UAC':                        "École Nationale d'Administration (ENA)",
    'EPAC / UAC':                       "École Polytechnique d'Abomey-Calavi (EPAC)",
    'ENEAM / UAC':                      "École Nationale d'Économie Appliquée et de Management (ENEAM)",
    'ENSTIC / UAC':                     "École Nationale Supérieure des Sciences et Techniques de l'Information (ENSTIC)",
    'ENS / UAC':                        'École Normale Supérieure (ENS) Porto-Novo',
    'FASEG / UAC':                      'Faculté des Sciences Économiques et de Gestion (FASEG) / UAC',
    'FAST / UAC':                       'Faculté des Sciences et Techniques (FAST) / UAC',
    'FADESP / UAC':                     'Faculté de Droit et de Science Politique (FADESP) / UAC',
    'FASHS / UAC':                      'Faculté des Sciences Humaines et Sociales (FASHS) / UAC',
    'FLLAC / UAC':                      'Faculté des Lettres, Langues, Arts et Communications (FLLAC) / UAC',
    'FSS / UAC':                        'Faculté des Sciences de la Santé (FSS) / UAC',
    'FSA / UAC':                        'Faculté des Sciences Agronomiques (FSA) / UAC',
    'IFRI / UAC':                       "Institut de Formation et de Recherche en Informatique (IFRI) / UAC",
    'IMSP / UAC':                       'Institut de Mathématiques et de Sciences Physiques (IMSP) / UAC',
    'INJEPS / UAC':                     "Institut National de la Jeunesse, de l'Éducation Physique et du Sport (INJEPS) / UAC",
    'FM / UP':                          'Faculté de Médecine (FM) / UP',
    'FADSEG / UP':                      'Faculté des Sciences Économiques et de Gestion (FADSEG) / UP',
    'FDSP / UP':                        'Faculté de Droit et de Science Politique (FDSP) / UP',
    'FLASH / UP':                       'Faculté des Lettres, Arts et Sciences Humaines (FLASH) / UP',
    'FA / UP':                          "Faculté d'Agronomie (FA) / UP",
    'INJEPS / UP':                      "Institut National de la Jeunesse, de l'Éducation Physique et du Sport (INJEPS) / UP",
    'IUT / UP':                         'Institut Universitaire de Technologie (IUT) / UP',
    'IFSIO / UP':                       'Institut de Formation en Soins Infirmiers et Obstétricaux (IFSIO) / UP',
    'ENSTP / UNSTIM':                   "École Nationale Supérieure des Travaux Publics (ENSTP) / UNSTIM",
    'ENSGEP / UNSTIM':                  "École Nationale Supérieure de Génie Énergétique et Procédés (ENSGEP) / UNSTIM",
    'ENSGMM / UNSTIM':                  "École Nationale Supérieure de Génie Mathématique et Modélisation (ENSGMM) / UNSTIM",
    'INSPEI / UNSTIM':                  "Institut National Supérieur des Classes Préparatoires aux Études d'Ingénieur (INSPEI) / UNSTIM",
    'INSTI / UNSTIM':                   "Institut National Supérieur de Technologie Industrielle (INSTI) / UNSTIM",
    'ENS Natitingou / UNSTIM':          'École Normale Supérieure de Natitingou / UNSTIM',
    'UNA':                              "Université Nationale d'Agriculture (UNA)",
    'UATM GASA Formation':              'Université Africaine de Technologie et de Management (UATM)',
    'IRGIB Africa Université':          'IRGIB Africa Université',
    'UCAO Bénin':                       "Université Catholique de l'Afrique de l'Ouest (UCAO)",
    'UPAO Bénin':                       "Université Protestante de l'Afrique de l'Ouest (UPAO)",
    'Les Cours Sonou':                  'Les Cours Sonou',
    'ESAE Bénin':                       "École Supérieure d'Administration, d'Économie et de Journalisme (ESAE)",
    'ESEP Le Beger':                    "École Supérieure d'Enseignement Professionnel Le Berger (ESEP)",
    'ESGTIC Bénin':                     'École Supérieure de Génie Télécoms et TIC (ESGTIC)',
    'ESMER Bénin':                      'École Supérieure des Métiers des Énergies Renouvelables (ESMER)',
    'École Supérieure Sainte Félicité': 'École Supérieure Sainte Félicité',
    'École Supérieure Jean Michel Le Faucon': 'École Supérieure Jean Michel Le Faucon',
    'HECM Bénin':                       'Haute École de Commerce et de Management (HECM)',
    'Institut Jean Paul II':            'Institut Jean Paul II',
    'VERECHAGUINE':                     'École Supérieure de Génie Civil Verechaguine A.K.',
    'ISCG Bénin':                       'Institut Supérieur de Commerce et de Gestion (ISCG)',
    'ISMA Bénin':                       "Institut Supérieur des Métiers de l'Audiovisuel (ISMA)",
    'ISM Adonaï':                       'Institut Supérieur de Management Adonaï (ISM Adonaï)',
    'IUP Bénin':                        'Institut Universitaire Panafricain (IUP)',
    'Pigier Bénin':                     'PIGIER Bénin',
    'École Supérieure de Management (ESM)': 'École Supérieure de Management (ESM)',
    'UPI-ONM Bénin':                    'Université Privée Internationale ONM (UPI-ONM)',
    'ISEG Bénin':                       "Institut Supérieur d'Études de Gestion (ISEG)",
    'ESIGT Bénin':                      "École Supérieure d'Ingénieur Géomètre Topographe (ESIGT)",
    'ESGIS Bénin':                      "École Supérieure de Gestion d'Informatique et de Sciences (ESGIS)",
    'IIM Bénin':                        'Institut International de Management (IIM)',
    'IUST-AS Bénin':                    'Institut Universitaire des Sciences et Techniques AS (IUST-AS)',
    'EFES Sapientia':                   'École de Formation des Enseignants du Secondaire Sapientia (EFES)',
    'ISMT Saint Salomon':               'Institut Supérieur des Métiers et Technologies Saint Salomon (ISMT)',
    'ESCAE Bénin':                      "École Supérieure de Commerce et d'Administration des Entreprises (ESCAE)",
    'ESPERANZA':                        'Institut ESPERANZA',
    'CIFEC Bénin':                      "Centre International de Formation et d'Études Comptables (CIFEC)",
    'African School of Economics (ASE)': 'African School of Economics (ASE)',
    'École Supérieure de Gestion Serena': 'École Supérieure de Gestion Serena',
    'POLYTECH ADA':                     'POLYTECH ADA',
}

# ─── Script d'insertion idempotent ─────────────────────────────────────────────

def seed():
    create_db_and_tables()

    with Session(engine) as session:
        existing_filieres = {
            f.nom: f for f in session.exec(select(Filiere)).all()
        }
        existing_univs = {
            u.nom: u for u in session.exec(select(Universite)).all()
        }
        existing_formations = {
            (f.id_filiere, f.id_universite)
            for f in session.exec(select(Formation)).all()
        }

        nb_filieres_new = 0
        nb_formations_new = 0
        nb_skip_f = 0
        nb_skip_form = 0

        for data in FILIERES:
            nom = data['nom']
            if nom not in existing_filieres:
                filiere = Filiere(
                    nom=nom,
                    domaine=data['domaine'],
                    duree_theorique=data['duree_theorique'],
                    salaire_median_p50=data['salaire_median_p50'],
                    taux_insertion=data['taux_insertion'],
                    indice_saturation=data['indice_saturation'],
                    tendance_ia=data['tendance_ia'],
                    tendance_curricula_marche=data['tendance_curricula_marche'],
                    profil_riasec_dominant=data['profil_riasec_dominant'],
                    veto_factors=data['veto_factors'],
                    poids_scoring=data['poids_scoring'],
                )
                session.add(filiere)
                session.flush()
                existing_filieres[nom] = filiere
                nb_filieres_new += 1
                print(f"  ✅ Filière ajoutée : {nom}")
            else:
                nb_skip_f += 1

            filiere_obj = existing_filieres[nom]

            for etab_key in data.get('etablissements', []):
                univ_nom = ETAB_MAP.get(etab_key)
                if not univ_nom:
                    print(f"  ⚠️  Clé ETAB_MAP inconnue : {etab_key!r}")
                    continue

                if univ_nom not in existing_univs:
                    univ = Universite(nom=univ_nom)
                    session.add(univ)
                    session.flush()
                    existing_univs[univ_nom] = univ
                    print(f"     + Université créée : {univ_nom}")

                univ_obj = existing_univs[univ_nom]
                pair = (filiere_obj.id_filiere, univ_obj.id_universite)

                if pair not in existing_formations:
                    formation = Formation(
                        id_filiere=filiere_obj.id_filiere,
                        id_universite=univ_obj.id_universite,
                    )
                    session.add(formation)
                    existing_formations.add(pair)
                    nb_formations_new += 1
                else:
                    nb_skip_form += 1

        session.commit()

        print("\n" + "=" * 55)
        print(f"  ✅ {nb_filieres_new} filières insérées  ({nb_skip_f} déjà en base)")
        print(f"  ✅ {nb_formations_new} formations insérées ({nb_skip_form} déjà en base)")

        total = len(session.exec(select(Filiere)).all())
        from collections import Counter
        domaines = Counter(
            f.domaine for f in session.exec(select(Filiere)).all()
        )
        print(f"\n  Total filières en base : {total}")
        print(f"  Domaines ({len(domaines)}) :")
        for dom, count in sorted(domaines.items()):
            print(f"    {dom:40s} {count:3d}")
        print("=" * 55)


if __name__ == '__main__':
    seed()
